### ISSUE TITLE
Network issues should not cause permanent downgrade to long polling

### ISSUE THREAD

**Issue by jfarcand** [Atmosphere/atmosphere-javascript#151]
Atmosphere/atmosphere#1861

**Comment by dozed** [comment]
One problem is that `_request.transport` is overwritten by `_request.fallbackTransport` in `reconnectWithFallbackTransport` and therefore the original user configuration is lost (https://github.com/Atmosphere/atmosphere-javascript/blob/master/modules/javascript/src/main/webapp/javascript/atmosphere.js#L1723-L1728).

My first idea was to add a flag `usesFallbackTransport` and then infer the transport from the configuration like this:

```javascript
/**
 * Returns the currently used transport, either main transport or fallback transport.
 * @private
 */
function _transport() {
    if (!_usesFallbackTransport) {
        return _request.transport;
    } else {
        return _request.fallbackTransport;
    }
}

/**
 * Returns the currently used method, either main method or fallback method.
 * @private
 */
function _method() {
    if (!_usesFallbackTransport) {
        return _request.method;
    } else {
        return _request.fallbackMethod;
    }
}
```

This does not work everywhere, since often the request is passed as a function argument.

**Comment by dozed** [comment]
Also when having both transport and fallbackTransport as websocket (as a workaround), this prevents re-connecting with websocket as fallbackTransport: https://github.com/Atmosphere/atmosphere-javascript/blob/master/modules/javascript/src/main/webapp/javascript/atmosphere.js#L1471-L1472

Commenting it out leads to a correct re-connect. But there is surely a reason why the guard is there in the first place?
