### ISSUE TITLE
IE beforeunload call causing disconnect

### ISSUE THREAD

**Issue by seamusmac** [Atmosphere/atmosphere-javascript#156]
See discussion at 
https://groups.google.com/forum/#!topic/atmosphere-framework/FUFKTSdIT4A

**Comment by jfarcand** [comment]
@oyvindhorneland :-) This is a regression from #143 . Any recommendation on how both FF and IE can handle this?

**Comment by oyvindhorneland** [comment]
To link the issues together:
* [Firefox reconnects instead of close when navigating away from current page #143](https://github.com/Atmosphere/atmosphere-javascript/issues/143)
* [Pull request #144 with fix for Firefox](https://github.com/Atmosphere/atmosphere-javascript/pull/144/)

And from the discussion in https://groups.google.com/forum/#!topic/atmosphere-framework/FUFKTSdIT4A
* http://codecorner.galanter.net/2011/10/20/onbeforeunload-event-is-fired-on-click/

@jfarcand Sorry, not yet. Need to check if we in beforeunload can detect that it's not really a navigation away from the current page.

**Comment by oyvindhorneland** [comment]
Referencing some similar issues and workarounds for beforeunload event
* http://stackoverflow.com/questions/23677001/jquery-window-onbeforeunload-not-working-with-a-href-javascript-function
* http://stackoverflow.com/questions/7650063/how-can-i-prevent-window-onbeforeunload-from-being-triggered-by-javascript-href
* https://developer.mozilla.org/en-US/docs/Web/Events/beforeunload
* https://msdn.microsoft.com/en-us/library/ie/ms536907%28v=vs.85%29.aspx

**Comment by oyvindhorneland** [comment]
While there seems to be a lot of advice saying use onClick and not href with javascript as well as various workarounds for those type of links, perhaps it's best for compatibility reasons to revisit #143 and see if we can get FF working with the unload event.

@jfarcand Any thoughs regarding an alternative solution for #143? FF was working in 2.2.5, but 2.2.6 introduced the "reconnect before close" behavior.

**Comment by seamusmac** [comment]
@jfarcand Any thoughts on this one? 
I was looking at #143, and I think that will need to be reverted. Maybe reopen it
Probably best to fix the firefox reconnect issue some other way.

**Comment by jfarcand** [comment]
@seamusmac I agree, I just don't have the cycle to test this week. If you have time, do me a favor and do a pull request with the revert and I will start from there. Thanks

**Comment by seamusmac** [comment]
@jfarcand Done, let me know if you need anything else. Thanks.
