### ISSUE TITLE
Firefox errors in console (from PrimeFaces)

### ISSUE THREAD

**Issue by melloware** [Atmosphere/atmosphere-javascript#226]
These two issues were reported in PrimeFaces that I have traced to the atmosphere JS file.

https://github.com/primefaces/primefaces/issues/2447

https://github.com/primefaces/primefaces/issues/2394

These errors only appear in Firefox not in IE or Chrome.

**Comment by salviof** [comment]
Up;

**Comment by olivergg** [comment]
+1 This is quite embarrassing since long-polling used to be a fallback transport mode when WebSocket did not work on some network.... 
I guess the issue is related to Firefox, since I've had a similar issue on a production application that did not change the atmosphere version over the last past months.
